name: one_loop
description: "Loop one audio"
publish_to: 'none'
version: 0.2.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter_localizations:
    sdk: flutter
  file_picker: ^10.3.8
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.9.1
  get: ^4.7.3
  just_audio: ^0.10.5
  package_info_plus: ^9.0.0
  path_provider: ^2.1.5
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.3
  path: ^1.9.1
  forui: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/